### ISSUE TITLE
Arduino library wrapper misses prebuilt themes

### ISSUE THREAD

**Issue by ramonschepers** [littlevgl/lv_projects#4]
As title states. It gives me "undefined reference to" messages.

I'm on phone now so I can't get into depth now aside from the fact I replaced the lvgl library to 5.1 and replaced the lvgl_conf.h file (yes, I enabled theming in the config file)

**Comment by kisvegabor** [comment]
Hi,

I updates the Arduino library to v5.1.
I tested with `lv_theme_alien_init(210, NULL);` and it worked for me.

Check it please with the updated version.

**Comment by ramonschepers** [comment]
seems the error is within the Zen theme, as the Alien theme compiles
